# Generated by Django 5.0.2 on 2024-02-23 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0018_station_sheetid_alter_code_employe_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_employe',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 23, 18, 3, 50, 354838)),
        ),
    ]
