# Generated by Django 5.0.2 on 2024-02-28 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0019_alter_code_employe_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_employe',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 28, 16, 16, 41, 744308, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employe',
            name='Date_Recrutement',
            field=models.DateField(default=datetime.datetime(2024, 2, 28, 16, 16, 41, 746315, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employe',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
