# Generated by Django 5.0.2 on 2024-03-02 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0022_alter_employe_date_recrutement'),
    ]

    operations = [
        migrations.CreateModel(
            name='month_stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=3)),
                ('Absent', models.IntegerField()),
                ('Travail', models.IntegerField()),
                ('Mission', models.IntegerField()),
                ('Conge', models.IntegerField()),
                ('RS', models.IntegerField()),
                ('Eve_fam', models.IntegerField()),
                ('Malade', models.IntegerField()),
                ('Absence_autori', models.IntegerField()),
                ('Employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointage.employe')),
            ],
        ),
    ]
