# Generated by Django 5.0.2 on 2024-03-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0023_month_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last_update',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='month_stat',
            name='Absence_autori',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month_stat',
            name='Absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month_stat',
            name='Conge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month_stat',
            name='Eve_fam',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month_stat',
            name='Malade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month_stat',
            name='Mission',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month_stat',
            name='RS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month_stat',
            name='Travail',
            field=models.IntegerField(default=0),
        ),
    ]
