# Generated by Django 5.0.2 on 2024-03-03 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0024_alter_last_update_id_alter_month_stat_absence_autori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_employe',
            name='open_to_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='month_stat',
            name='Date',
            field=models.DateField(default=datetime.date(2024, 3, 3)),
        ),
    ]
