# Generated by Django 5.0.2 on 2024-03-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0025_code_employe_open_to_edit_alter_month_stat_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Last_Update',
        ),
        migrations.DeleteModel(
            name='month_stat',
        ),
    ]
