# Generated by Django 5.0.2 on 2024-03-03 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0026_delete_last_update_delete_month_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month_stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=6)),
                ('absent', models.IntegerField(default=0)),
                ('travail', models.IntegerField(default=0)),
                ('mission', models.IntegerField(default=0)),
                ('conge', models.IntegerField(default=0)),
                ('rs', models.IntegerField(default=0)),
                ('eve_fam', models.IntegerField(default=0)),
                ('mld', models.IntegerField(default=0)),
                ('abs_autorise', models.IntegerField(default=0)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointage.employe')),
            ],
        ),
    ]
