# Generated by Django 5.0.2 on 2024-03-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0028_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='recup',
            field=models.IntegerField(default=0),
        ),
    ]
