# Generated by Django 5.0.2 on 2024-03-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0030_profile_date_delete_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date',
            new_name='last_update',
        ),
    ]
