# Generated by Django 5.0.2 on 2024-03-03 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0031_rename_date_profile_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_update',
        ),
        migrations.AddField(
            model_name='station',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
