# Generated by Django 5.0.2 on 2024-03-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0032_remove_profile_last_update_station_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='last_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
