# Generated by Django 5.0.2 on 2024-03-03 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0033_alter_station_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_employe',
            name='last_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
