# Generated by Django 5.0.2 on 2024-03-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0034_code_employe_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_employe',
            name='stored',
            field=models.BooleanField(default=False),
        ),
    ]
