# Generated by Django 5.0.2 on 2024-03-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0036_employe_remboursement_mois_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('date_of_validation', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
