# Generated by Django 5.0.2 on 2024-03-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0037_validdate_employe_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='validdate',
            name='month',
            field=models.IntegerField(default=2),
        ),
    ]
