# Generated by Django 5.0.2 on 2024-03-14 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0038_validdate_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_sheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheets_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='sheets_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pointage.user_sheets'),
        ),
    ]
