# Generated by Django 5.0.2 on 2024-03-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0039_user_sheets_station_sheets_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='remboursement_mois',
        ),
    ]
